<?php

namespace App\Constant\CaptainPayment\PaymentToCaptain;

final class CaptainPaymentResultConstant
{
    const CAPTAIN_PAYMENT_CREATE_FOR_CAPTAIN_FINANCIAL_DAILY_ERROR_CONST = 180;

    const CAPTAIN_PAYMENT_NOT_EXIST = 181;

    const CAPTAIN_PAYMENT_LINKED_TO_CAPTAIN_FINANCIAL_DAILY_CONST = 183;

    const CAPTAIN_PAYMENT_LINKED_TO_CAPTAIN_FINANCIAL_DUE_CONST = 184;
}
