// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI1NPRqgXwAHgRBuy_7IAXnnvM8XT-Fu0',
    appId: '1:410273886458:web:78390256f1f5efb11f1943',
    messagingSenderId: '410273886458',
    projectId: 'c4d-app-c299b',
    authDomain: 'c4d-app-c299b.firebaseapp.com',
    databaseURL: 'https://c4d-app-c299b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'c4d-app-c299b.appspot.com',
    measurementId: 'G-XSMNHCSQGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu7Ht94vcMesIkCd8kkHiBCG8OlI2ijuM',
    appId: '1:410273886458:android:49a35b4f1a935afb1f1943',
    messagingSenderId: '410273886458',
    projectId: 'c4d-app-c299b',
    databaseURL: 'https://c4d-app-c299b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'c4d-app-c299b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmhSOcWvDFVu3eb3J1B2aZVcaifcqlVPo',
    appId: '1:410273886458:ios:c43e50b4a4f0b6271f1943',
    messagingSenderId: '410273886458',
    projectId: 'c4d-app-c299b',
    databaseURL: 'https://c4d-app-c299b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'c4d-app-c299b.appspot.com',
    androidClientId: '410273886458-fd6s8r736otlbkkqkmmbdtas3garq9lm.apps.googleusercontent.com',
    iosClientId: '410273886458-mj006u4dq0co8d9m01mv1s6mo5f03lts.apps.googleusercontent.com',
    iosBundleId: 'de.yessoft.c4d-dashboard',
  );
}
