App\Request\Subscription\SubscriptionCreateRequest:
    properties:
        package:
            - NotBlank: ~

App\Request\Subscription\SubscriptionNextRequest:
    properties:
        package:
            - NotBlank: ~

App\Request\Admin\Package\PackageCreateRequest:
    properties:
        name:
            - NotBlank: ~
        cost:
            - NotBlank: ~
        carCount:
            - NotBlank: ~
        orderCount:
            - NotBlank: ~
        packageCategory:
            - NotBlank: ~
        expired:
            - NotBlank: ~

App\Request\Admin\Package\PackageUpdateRequest:
    properties:
        id:
            - NotBlank: ~
        name:
            - NotBlank: ~
        cost:
            - NotBlank: ~
        carCount:
            - NotBlank: ~
        orderCount:
            - NotBlank: ~

App\Request\Admin\Package\PackageStatusUpdateRequest:
    properties:
        id:
            - NotBlank: ~
        status:
            - NotBlank: ~

App\Request\StoreOwner\StoreOwnerProfileUpdateRequest:
    properties:
        storeOwnerName:
            - NotBlank: ~

App\Request\StoreOwnerBranch\StoreOwnerBranchCreateRequest:
    properties:
        location:
            - NotBlank: ~
        name:
            - NotBlank: ~
        branchPhone:
            - NotBlank: ~

App\Request\StoreOwnerBranch\StoreOwnerBranchUpdateRequest:
    properties:
        id:
            - NotBlank: ~
        location:
            - NotBlank: ~
        name:
            - NotBlank: ~
        branchPhone:
            - NotBlank: ~

App\Request\StoreOwnerBranch\StoreOwnerBranchDeleteRequest:
    properties:
        id:
            - NotBlank: ~

App\Request\StoreOwnerBranch\StoreOwnerMultipleBranchesCreateRequest:
    properties:
        branches:
            - NotBlank: ~

App\Request\StoreOwnerBranch\StoreOwnerCompleteAccountStatusUpdateRequest:
    properties:
        storeOwnerId:
            - NotBlank: ~
        completeAccountStatus:
            - NotBlank: ~

App\Request\CompanyInfo\CompanyInfoUpdateRequest:
    properties:
        id:
            - NotBlank: ~

App\Request\StoreOwner\StoreOwnerProfileStatusUpdateByAdminRequest:
    properties:
        id:
            - NotBlank: ~
        status:
            - NotBlank: ~

App\Request\StoreOwner\StoreOwnerProfileUpdateByAdminRequest:
    properties:
        id:
            - NotBlank: ~

App\Request\Order\OrderCreateRequest:
    properties:
        branch:
            - NotBlank: ~

App\Request\Admin\Package\PackageCategoryUpdateRequest:
    properties:
        id:
            - NotBlank: ~
        name:
            - NotBlank: ~

App\Request\Admin\Notification\AdminNotificationToUsersCreateRequest:
    properties:
        title:
            - NotBlank: ~
        msg:
            - NotBlank: ~
        appType:
            - NotBlank: ~

App\Request\Admin\Notification\AdminNotificationToUsersUpdateRequest:
    properties:
        id:
            - NotBlank: ~
        title:
            - NotBlank: ~
        msg:
            - NotBlank: ~
        appType:
            - NotBlank: ~

App\Request\Rate\RatingCreateRequest:
    properties:
        rating:
            - NotBlank: ~
        rater:
            - NotBlank: ~
        rated:
            - NotBlank: ~

App\Request\Main\OrderStateUpdateBySuperAdminRequest:
    properties:
        id:
            - NotBlank: ~
        state:
            - NotBlank: ~

App\Request\Admin\CaptainOffer\CaptainOfferCreateRequest:
    properties:
        carCount:
            - NotBlank: ~
        status:
            - NotBlank: ~
        expired:
            - NotBlank: ~
        price:
            - NotBlank: ~

App\Request\Admin\CaptainOffer\CaptainOfferUpdateRequest:
    properties:
        id:
            - NotBlank: ~
        carCount:
            - NotBlank: ~
        expired:
            - NotBlank: ~
        price:
            - NotBlank: ~

App\Request\Admin\CaptainOffer\CaptainOfferStatusUpdateRequest:
    properties:
        id:
            - NotBlank: ~
        status:
            - NotBlank: ~

App\Request\Admin\Captain\CaptainProfileStatusUpdateByAdminRequest:
    properties:
        id:
            - NotBlank: ~
        status:
            - NotBlank: ~

App\Request\Admin\Captain\CaptainProfileUpdateByAdminRequest:
    properties:
        id:
            - NotBlank: ~
        captainName:
            - NotBlank: ~

App\Request\Order\OrderUpdateByCaptainRequest:
    properties:
        id:
            - NotBlank: ~
        state:
            - NotBlank: ~

App\Request\Order\OrderChatRoomRequest:
    properties:
        orderId:
            - NotBlank: ~

App\Request\Admin\Package\PackageCategoryCreateByAdminRequest:
    properties:
        name:
            - NotBlank: ~

App\Request\Order\OrderUpdateCaptainOrderCostRequest:
    properties:
        id:
            - NotBlank: ~
        captainOrderCost:
            - NotBlank: ~

App\Request\Order\OrderUpdateCaptainArrivedRequest:
    properties:
        id:
            - NotBlank: ~

App\Request\Admin\AdminProfile\AdminProfileRequest:
    properties:
        id:
            - NotBlank: ~
        name:
            - NotBlank: ~

App\Request\Admin\AdminProfile\AdminProfileStatusUpdateRequest:
    properties:
        id:
            - NotBlank: ~

App\Request\Notification\NotificationTokensCreateRequest:
    properties:
        appType:
            - NotBlank: ~
        userId:
            - NotBlank: ~

App\Request\Notification\NotificationFirebaseFromAdminRequest:
    properties:
        otherUserID:
            - NotBlank: ~

App\Request\Admin\StoreOwnerPayment\AdminStoreOwnerPaymentCreateRequest:
    properties:
        amount:
            - NotBlank: ~
        store:
            - NotBlank: ~

App\Request\Notification\NotificationFirebaseBySuperAdminCreateRequest:
    properties:
        title:
            - NotBlank: ~
        messageBody:
            - NotBlank: ~

App\Request\Admin\CaptainFinancialSystem\AdminCaptainFinancialSystemAccordingToCountOfHoursCreateRequest:
    properties:
        countHours:
            - NotBlank: ~
        compensationForEveryOrder:
            - NotBlank: ~
        salary:
            - NotBlank: ~

App\Request\Admin\SupplierCategory\SupplierCategoryCreateByAdminRequest:
    properties:
        name:
            - NotBlank: ~

App\Request\Admin\SupplierCategory\SupplierCategoryUpdateByAdminRequest:
    properties:
        id:
            - NotBlank: ~
        name:
            - NotBlank: ~

App\Request\Admin\SupplierCategory\SupplierCategoryStatusUpdateByAdminRequest:
    properties:
        id:
            - NotBlank: ~
        status:
            - NotNull: ~

App\Request\Admin\CaptainFinancialSystem\AdminCaptainFinancialSystemAccordingToCountOfOrdersCreateRequest:
    properties:
        countOrdersInMonth:
            - NotBlank: ~
        salary:
            - NotBlank: ~
        monthCompensation:
            - NotBlank: ~
        bounceMaxCountOrdersInMonth:
            - NotBlank: ~
        bounceMinCountOrdersInMonth:
            - NotBlank: ~

App\Request\Admin\CaptainFinancialSystem\AdminCaptainFinancialSystemAccordingOnOrderCreateRequest:
    properties:
        categoryName:
            - NotBlank: ~
        countKilometersFrom:
            - NotBlank: ~
        countKilometersTo:
            - NotBlank: ~
        amount:
            - NotBlank: ~

App\Request\User\UserRegisterRequest:
    properties:
        userId:
            - NotBlank: ~
        password:
            - NotBlank: ~

App\Request\Supplier\SupplierProfileUpdateRequest:
    properties:
        supplierName:
            - NotBlank: ~

App\Request\CaptainFinancialSystem\CaptainFinancialSystemDetailRequest:
    properties:
        captainFinancialSystemType:
            - NotBlank: ~
        captainFinancialSystemId:
            - NotBlank: ~
         
App\Request\Admin\CaptainPayment\AdminCaptainPaymentCreateRequest:
    properties:
        amount:
            - NotBlank: ~
        captain:
            - NotBlank: ~
        captainFinancialDuesId:
            - NotBlank: ~
        status:
            - NotBlank: ~

App\Request\Admin\SupplierProfile\SupplierProfileStatusUpdateByAdminRequest:
    properties:
        id:
            - NotBlank: ~
        status:
            - NotNull: ~

App\Request\Announcement\AnnouncementCreateRequest:
    properties:
        price:
            - NotBlank: ~
        quantity:
            - NotBlank: ~

App\Request\Announcement\AnnouncementUpdateRequest:
    properties:
        id:
            - NotBlank: ~
        price:
            - NotBlank: ~
        quantity:
            - NotBlank: ~

App\Request\Announcement\AnnouncementStatusUpdateRequest:
    properties:
        id:
            - NotBlank: ~
        status:
            - NotNull: ~

App\Request\Admin\Announcement\AnnouncementAdministrationStatusUpdateRequest:
    properties:
        id:
            - NotBlank: ~
        administrationStatus:
            - NotNull: ~

App\Request\Admin\SupplierProfile\SupplierProfileUpdateByAdminRequest:
    properties:
        id:
            - NotBlank: ~
        supplierName:
            - NotNull: ~

App\Request\Admin\CaptainFinancialSystem\AdminCaptainFinancialSystemAccordingOnOrderUpdateRequest:
    properties:
        id:
            - NotBlank: ~
        categoryName:
            - NotBlank: ~
        countKilometersFrom:
            - NotBlank: ~
        countKilometersTo:
            - NotBlank: ~
        amount:
            - NotBlank: ~
            
App\Request\Admin\CaptainFinancialSystem\AdminCaptainFinancialSystemAccordingToCountOfHoursUpdateRequest:
    properties:
        id:
            - NotBlank: ~
        countHours:
            - NotBlank: ~
        compensationForEveryOrder:
            - NotBlank: ~
        salary:
            - NotBlank: ~

App\Request\Admin\CaptainFinancialSystem\AdminCaptainFinancialSystemAccordingToCountOfOrdersUpdateRequest:
    properties:
        id:
            - NotBlank: ~
        countOrdersInMonth:
            - NotBlank: ~
        salary:
            - NotBlank: ~
        monthCompensation:
            - NotBlank: ~
        bounceMaxCountOrdersInMonth:
            - NotBlank: ~
        bounceMinCountOrdersInMonth:
            - NotBlank: ~

App\Request\Admin\CaptainFinancialSystem\AdminCaptainFinancialSystemDetailUpdateRequest:
    properties:
        id:
            - NotBlank: ~
        status:
            - NotNull: ~

App\Request\Order\AnnouncementOrderCreateRequest:
    properties:
        announcement:
            - NotBlank: ~

App\Request\AnnouncementOrderDetails\AnnouncementOrderPriceOfferValueUpdateRequest:
    properties:
        id:
            - NotBlank: ~

App\Request\Order\BidDetailsCreateRequest:
    properties:
        supplierCategory:
            - NotBlank: ~
        storeOwner:
            - NotBlank: ~
        branch:
            - NotBlank: ~

App\Request\PriceOffer\PriceOfferCreateRequest:
    properties:
        bidDetails:
            - NotBlank: ~
        priceOfferValue:
            - NotBlank: ~
        offerDeadline:
            - NotBlank: ~
        deliveryCar:
            - NotBlank: ~

App\Request\PriceOffer\PriceOfferStatusUpdateRequest:
    properties:
        id:
            - NotBlank: ~
        priceOfferStatus:
            - NotBlank: ~

App\Request\Admin\DeliveryCar\DeliveryCarCreateRequest:
    properties:
        carModel:
            - NotBlank: ~
        deliveryCost:
            - NotBlank: ~

App\Request\Admin\User\UserIdUpdateRequest:
    properties:
        currentUserId:
            - NotBlank: ~
        newUserId:
            - NotBlank: ~
        password:
            - NotBlank: ~

App\Request\Admin\CaptainAmountFromOrderCash\CaptainAmountFromOrderCashFilterGetRequest:
    properties:
        captainId:
            - NotBlank: ~
        fromDate:
            - NotBlank: ~
        toDate:
            - NotBlank: ~

App\Request\Admin\StoreOwnerDuesFromCashOrders\StoreOwnerDuesFromCashOrdersFilterGetRequest:
    properties:
        storeId:
            - NotBlank: ~
        fromDate:
            - NotBlank: ~
        toDate:
            - NotBlank: ~

App\Request\Admin\CaptainPayment\AdminCaptainPaymentToCompanyForOrderCashCreateRequest:
    properties:
        amount:
            - NotBlank: ~
        captain:
            - NotBlank: ~
        fromDate:
            - NotBlank: ~
        toDate:
            - NotBlank: ~

App\Request\Order\SubOrderCreateRequest:
    properties:
        branch:
            - NotBlank: ~
        primaryOrder:
            - NotBlank: ~
            
App\Request\Verification\VerifyCodeRequest:
    properties:
        user:
            - NotBlank: ~
        code:
            - NotBlank: ~
