<?php

namespace App\Constant\Order;

final class OrderCancelledByUserAndAtStateConstant
{
    const ORDER_CANCELLED_BY_STORE_AND_AT_ON_WAY_TO_PICK_ORDER_STATE_CONST = 190;

    const ORDER_CANCELLED_BY_STORE_AND_AT_IN_STORE_STATE_CONST = 191;

    const ORDER_CANCEL_USER_AND_STATE_ARRAY = [
        'ORDER_CANCELLED_BY_STORE_AND_AT_ON_WAY_TO_PICK_ORDER_STATE_CONST' => 190,
        'ORDER_CANCELLED_BY_STORE_AND_AT_IN_STORE_STATE_CONST' => 191,
        'ORDER_CANCELLED_BY_ADMIN_AND_AT_IN_STORE_STATE_CONST' => 189,
        'ORDER_CANCELLED_BY_ADMIN_AND_AT_ONGOING_STATE_CONST' => 192,
        'ORDER_CANCELLED_BY_ADMIN_AND_AT_DELIVERED_STATE_CONST' => 193,
    ];
}
