<?php

namespace App\Constant\Subscription;

final class SubscriptionDetailsConstant
{
    const SUBSCRIPTION_DETAILS_NOT_FOUND = 120;

    const REMAINING_CARS_CAN_NOT_BE_UPDATED = 121;

    const REMAINING_ORDERS_CAN_NOT_BE_UPDATED = 122;

    const SUBSCRIPTION_REMAINING_ORDERS_IS_BIGGER_THAN_PACKAGE_ORDERS_CONST = 136;

    const SUBSCRIPTION_REMAINING_ORDERS_IS_LESS_THAN_ZERO_CONST = 137;

    const SUBSCRIPTION_REMAINING_ORDERS_IS_FINISHED = 142;

    const SUBSCRIPTION_REMAINING_CARS_IS_BIGGER_THAN_PACKAGE_CARS_CONST = 143;

    const SUBSCRIPTION_REMAINING_CARS_IS_EQUAL_TO_PACKAGE_CARS_COUNT_CONST = 144;

    const SUBSCRIPTION_REMAINING_CARS_IS_FINISHED = 145;

    const SUBSCRIPTION_REMAINING_CARS_IS_LESS_THAN_ZERO_CONST = 146;

    const SUBSCRIPTION_REMAINING_CARS_IS_VALID_CONST = 147;

    const SUBSCRIPTION_REMAINING_ORDERS_OUT_OF_LIMITS_CONST = 151;

    const SUBSCRIPTION_REMAINING_ORDERS_IS_VALID_CONST = 152;

    const SUBSCRIPTION_REMAINING_ORDERS_IS_EQUAL_TO_PACKAGE_ORDER_COUNT_CONST = 153;
}
